name: Build and Push laravel Image to Docker Hub

env:
  IMAGE_NAME: laravelbaseimage
  DOCKERFILE_PATH: Dockerfile
  DOCKER_HUB_USERNAME: nathanaj 
  DOCKER_HUB_REPOSITORY: narthanaj/laravelbaseimage

on: [push, workflow_dispatch]
  
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: docker.io
  
      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          platforms: linux/amd64, linux/arm64
          push: true
